name: chikin_airdrop_pool_client
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  #
  solana:
    git: https://github.com/ChikinDeveloper/dart-solana-lib

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
